name: Qualys WAS Scan 
on:
  push:
    branches:
      - master
jobs:
    Qualys_was_scan:
        runs-on: ubuntu-latest
        name: Qualys WAS Scan
        steps:
          - name: Checkout
            uses: actions/checkout@v3 
            with:
                fetch-depth: 0

          - name: Create the WAS XML file
            run: |
                xml_content='<ServiceRequest>
                <data>
                <WebApp>
                <url>{{ vars.SERVICE_URL }}</url>
                </WebApp>
                </data>
                </ServiceRequest>'
                
                # Specify the file name
                file_name="file.xml"
                
                # Write the content to the file
                echo "$xml_content" > "$file_name"
             
          - name: Update WAS App
            run: |
              $response=(curl --write-out "%{http_code}" --silent --output /dev/null  -u "${{ vars.QUALYS_USERNAME }}:${{ secrets.QUALYS_PASSWORD }}" -H "content-type: text/xml" -X "POST" --data-binary @file.xml "${{ vars.API_SERVER }}/qps/rest/3.0/update/was/webapp/${{ vars.WEBAPP_ID }}")
              if [ "$response" -ne 200 ]; then
                echo "Error: Received status code $response"
                exit 1  # This stops the pipeline if the status code is not 200
              else
                echo "Success: Received status code $response"
              fi
              
          - name: Qualys WAS scan action step
            uses: Qualys/github-action-qwas@main
            id: was
            with:
              API_SERVER: ${{ vars.API_SERVER }}
              QUALYS_USERNAME: ${{ vars.QUALYS_USERNAME }}
              QUALYS_PASSWORD: ${{ secrets.QUALYS_PASSWORD }}
              WEBAPP_ID: ${{ vars.WEBAPP_ID }}
              SCAN_NAME: ${{ vars.SCAN_NAME }}
              SCAN_TYPE: ${{ vars.SCAN_TYPE }}
              AUTH_RECORD: none
              AUTH_RECORD_ID: ""
              OPTION_PROFILE: useDefault
              OPTION_PROFILE_ID: ""
              CANCEL_OPTION: false
              CANCEL_HOURS: ""
              SEVERITY_CHECK: true
              SEVERITY_LEVEL: 1
              EXCLUDE: ""
              FAIL_ON_SCAN_ERROR: false
              WAIT_FOR_RESULT: true
              INTERVAL: 	5
              TIMEOUT: 350
